### ISSUE TITLE
Firestore call to gRPC works fine on my mac but throws exception when I deployed the war on azure linux app service

### ISSUE THREAD

**Issue by dardison** [googleapis/java-firestore#1154]
#### Environment details

 * Operating System version: Linux Alpine 3.9
 * Firebase SDK Admin version: 8.1.0
 * Library version: Java 8
 * Firebase Product: firestore database (auth, database, storage, etc)
 * From linux console:
```
02c3d1e2371f:/home# java -version
Picked up JAVA_TOOL_OPTIONS:  -Djava.net.preferIPv4Stack=true
openjdk version "1.8.0_212"
OpenJDK Runtime Environment (Zulu 8.38.0.13-linux-musl-x64)-Microsoft-Azure-restricted (build 1.8.0_212-b04)
OpenJDK 64-Bit Server VM (Zulu 8.38.0.13-linux-musl-x64)-Microsoft-Azure-restricted (build 25.212-b04, mixed mode)
```

#### Steps to reproduce

 My app is a Java Server app deployed on a Tomcat 8.5 Server and that connects with Firebase thru Firebase Admin SDK.
Everything works fine while I running on my localhost Tomcat instance on my mac but when I deployed to an Azure app service, which is a Linux Alpine 3.9 I received Exception:
```
com.google.cloud.firestore.FirestoreException: java.lang.IllegalStateException: Could not find TLS ALPN provider; no working netty-tcnative, Conscrypt, or Jetty NPN/ALPN available
``` 

#### Stack trace
```
2022-12-22 18:56:25,126 ERROR BaseQueueProcessCallback:41 - Error en ejecucion cola:java.lang.IllegalStateException: Could not find TLS ALPN provider; no working netty-tcnative, Conscrypt, or Jetty NPN/ALPN available
com.google.cloud.firestore.FirestoreException: java.lang.IllegalStateException: Could not find TLS ALPN provider; no working netty-tcnative, Conscrypt, or Jetty NPN/ALPN available
        at com.google.cloud.firestore.FirestoreException.forIOException(FirestoreException.java:94)
        at com.google.cloud.firestore.FirestoreOptions$DefaultFirestoreRpcFactory.create(FirestoreOptions.java:91)
        at com.google.cloud.firestore.FirestoreOptions$DefaultFirestoreRpcFactory.create(FirestoreOptions.java:81)
        at com.google.cloud.ServiceOptions.getRpc(ServiceOptions.java:560)
        at com.google.cloud.firestore.FirestoreOptions.getFirestoreRpc(FirestoreOptions.java:365)
        at com.google.cloud.firestore.FirestoreImpl.<init>(FirestoreImpl.java:72)
        at com.google.cloud.firestore.FirestoreOptions$DefaultFirestoreFactory.create(FirestoreOptions.java:72)
        at com.google.cloud.firestore.FirestoreOptions$DefaultFirestoreFactory.create(FirestoreOptions.java:65)
        at com.google.cloud.ServiceOptions.getService(ServiceOptions.java:540)
        at com.google.firebase.cloud.FirestoreClient.<init>(FirestoreClient.java:51)
        at com.google.firebase.cloud.FirestoreClient.<init>(FirestoreClient.java:29)
        at com.google.firebase.cloud.FirestoreClient$FirestoreClientService.<init>(FirestoreClient.java:95)
        at com.google.firebase.cloud.FirestoreClient.getInstance(FirestoreClient.java:85)
        at com.google.firebase.cloud.FirestoreClient.getFirestore(FirestoreClient.java:78)
        at com.google.firebase.cloud.FirestoreClient.getFirestore(FirestoreClient.java:64)
        at com.areateclab.survey.server.firebase.FirebaseDAO.getDB(FirebaseDAO.java:36)
        at com.areateclab.survey.server.firebase.FirebaseDAO.createDocument(FirebaseDAO.java:42)
        at com.areateclab.survey.server.queue.survey.SurveyQueueProcess.execute(SurveyQueueProcess.java:26)
        at com.areateclab.survey.server.queue.survey.SurveyQueueProcess.execute(SurveyQueueProcess.java:15)
        at com.areateclab.survey.server.queue.QueueRecord.execute(QueueRecord.java:49)
        at com.areateclab.survey.server.queue.QueueProcessConsumer.run(QueueProcessConsumer.java:59)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: java.lang.IllegalStateException: Could not find TLS ALPN provider; no working netty-tcnative, Conscrypt, or Jetty NPN/ALPN available
        at com.google.cloud.firestore.spi.v1.GrpcFirestoreRpc.<init>(GrpcFirestoreRpc.java:141)
        at com.google.cloud.firestore.FirestoreOptions$DefaultFirestoreRpcFactory.create(FirestoreOptions.java:89)
        ... 20 more
Caused by: java.lang.IllegalStateException: Could not find TLS ALPN provider; no working netty-tcnative, Conscrypt, or Jetty NPN/ALPN available
        at io.grpc.netty.shaded.io.grpc.netty.GrpcSslContexts.defaultSslProvider(GrpcSslContexts.java:246)
        at io.grpc.netty.shaded.io.grpc.netty.GrpcSslContexts.configure(GrpcSslContexts.java:146)
        at io.grpc.netty.shaded.io.grpc.netty.GrpcSslContexts.forClient(GrpcSslContexts.java:95)
        at io.grpc.netty.shaded.io.grpc.netty.NettyChannelBuilder$DefaultProtocolNegotiator.newNegotiator(NettyChannelBuilder.java:623)
        at io.grpc.netty.shaded.io.grpc.netty.NettyChannelBuilder.buildTransportFactory(NettyChannelBuilder.java:529)
        at io.grpc.netty.shaded.io.grpc.netty.NettyChannelBuilder$NettyChannelTransportFactoryBuilder.buildClientTransportFactory(NettyChannelBuilder.java:188)
        at io.grpc.internal.ManagedChannelImplBuilder.build(ManagedChannelImplBuilder.java:630)
        at io.grpc.internal.AbstractManagedChannelImplBuilder.build(AbstractManagedChannelImplBuilder.java:264)
        at com.google.api.gax.grpc.InstantiatingGrpcChannelProvider.createSingleChannel(InstantiatingGrpcChannelProvider.java:360)
        at com.google.api.gax.grpc.InstantiatingGrpcChannelProvider.access$1800(InstantiatingGrpcChannelProvider.java:81)
        at com.google.api.gax.grpc.InstantiatingGrpcChannelProvider$1.createSingleChannel(InstantiatingGrpcChannelProvider.java:231)
        at com.google.api.gax.grpc.ChannelPool.create(ChannelPool.java:72)
        at com.google.api.gax.grpc.InstantiatingGrpcChannelProvider.createChannel(InstantiatingGrpcChannelProvider.java:241)
        at com.google.api.gax.grpc.InstantiatingGrpcChannelProvider.getTransportChannel(InstantiatingGrpcChannelProvider.java:219)
        at com.google.api.gax.rpc.ClientContext.create(ClientContext.java:199)
        at com.google.api.gax.rpc.ClientContext.create(ClientContext.java:133)
        at com.google.cloud.firestore.spi.v1.GrpcFirestoreRpc.<init>(GrpcFirestoreRpc.java:126)
        ... 21 more

```

#### External references such as API reference guides

- ?

### Versions of grpc and netty founded
- When search my dependencies for grpc this was the resulted versions
![DDFCCD55-8286-4DCE-B019-5AB97503B706](https://user-images.githubusercontent.com/1153392/209221800-bd7a68f2-158d-4a53-bbd0-08df3c73fb33.jpeg)
- When search my dependencies for netty this was the resulted versions
![FB5959F9-138C-4413-BEF7-92C75B24AB96](https://user-images.githubusercontent.com/1153392/209221927-2c6f48c2-8700-4305-bcbb-428399aa43c6.jpeg)

I was searching in google with not much success about the issue, most of the few links I found talk about missing libraries but I couldn't found missing libraries in my environment.
Also I tried adding this library that at first was not present in my environment but the error remains:
```
<dependency>
	        <groupId>io.netty</groupId>
	        <artifactId>netty-tcnative-boringssl-static</artifactId>
	        <version>2.0.34.Final</version>
</dependency>
```
Any help you could give me I will appreciated, I have no clue about how can I resolve the issue, thanks in advance.

**Comment by milaGGL** [comment]
Hi @dardison , thank you for reporting this and I am looking into it.  Our response will be slower than usual during the festival season, thank you for your understanding in advance.

**Comment by milaGGL** [comment]
Happy holidays, @dardison. So the app is working fine with Tomcat 8.5 server, but crashing on Linux Alpine 3.9. While looking into similar issues, there are some plausible theories worth checking out: 
1. There might be a Netty version conflict. 
Could you please provide a list of dependencies and their version numbers for further investigation?
Also, this link might be useful while checking the version combination: https://github.com/grpc/grpc-java/blob/master/SECURITY.md#netty. ie: netty-tcnative-boringssl-static 2.0.34.Final should be combined with netty-handler 4.1.52.Final.
3. There is a slim chance that it is a 32-bit VS. 64-bit conflict. Could you please double check the servers bit version? You might be able to fix the issue by changing the JAVA version or using Conscrypt/netty-tcnative instead.  Please check the recommendation for TLS for Android and non-Android apps: https://github.com/grpc/grpc-java/blob/master/SECURITY.md#tls-on-non-android

**Comment by dardison** [comment]
Happy Holidays to you too @milaGGL .
In reference to 1) 
I already provide you a list of dependencies in the images above, and as you can see for that image all the dependencies that were referenced to grpc or netty are there because of firebase-admin: 8.1.0. I didn't introduce any additional references, except for:
```
<dependency>
	        <groupId>io.netty</groupId>
	        <artifactId>netty-tcnative-boringssl-static</artifactId>
	        <version>2.0.34.Final</version>
</dependency>
```
as I mentioned above, this didn't produce any changes, the errors remains.
I don't know what additional information you need in reference to this topic, please advice.

In reference to 2)
I already check that the version of Java in the Linux Alpine is 64bits as I mentioned above too.
This is what Java version command line prints from the Linux Alpine console:
```
02c3d1e2371f:/home# java -version
Picked up JAVA_TOOL_OPTIONS:  -Djava.net.preferIPv4Stack=true
openjdk version "1.8.0_212"
OpenJDK Runtime Environment (Zulu 8.38.0.13-linux-musl-x64)-Microsoft-Azure-restricted (build 1.8.0_212-b04)
OpenJDK 64-Bit Server VM (Zulu 8.38.0.13-linux-musl-x64)-Microsoft-Azure-restricted (build 25.212-b04, mixed mode)
```
What additional information do you need on this topic?

**Comment by milaGGL** [comment]
It is difficult to debug without a reproducible code, please bear with me while trying possible solutions. 

I noticed that you are using the older version of Firebase Admin SDK. Would you be able to try it out with the [latest version](https://github.com/firebase/firebase-admin-java/releases/tag/v9.1.1)?  Newer sdk with newer grpc-netty-shaded should help eliminate some version conflict. 

Also, there is a similar issue reported under grpc-java, one of the [recommendation](https://github.com/grpc/grpc-java/issues/5369#issuecomment-751885384) is to use JAVA11.  Given that the JDK version you have is "1.8.0_212", and Java 8u252 added ALPN support, updating JAVA8 to a newer version worth a shot.

**Comment by dardison** [comment]
I cannot use Java11 because other compatibility issues, but I could try to move up in Java version 8 maybe java 1.8.0_252 could help.
I could also try to move up in Firebase Admin SDK version to the latest, let me try to do the upgrades  and I will let you know the results.

**Comment by dardison** [comment]
I have good news!!
I upgrade version of Java in the server to 8u322 and it works!!
```
c2419f95e854:/home# java -version
Picked up JAVA_TOOL_OPTIONS: -Xmx2752M -Djava.net.preferIPv4Stack=true 
openjdk version "1.8.0_322"
OpenJDK Runtime Environment (Temurin)(build 1.8.0_322-b06)
OpenJDK 64-Bit Server VM (Temurin)(build 25.322-b06, mixed mode)
c2419f95e854:/home# 
```
I didn't need to upgrade the Firebase Admin SDK

Thanks for your help @milaGGL 
Happy new year!

**Comment by milaGGL** [comment]
With pleasure. I am closing this ticket now. 
Happy new year, @dardison!
