### ISSUE TITLE
Firestore UNAVAILABLE - connection reset by peer

### ISSUE THREAD

**Issue by Amosss** [googleapis/java-firestore#267]
Hi

Environment: Java 8, admin sdk 6.13.0, ubuntu 18.0.4

#### Steps to reproduce
Please see point 2 in the following thread: https://github.com/firebase/firebase-admin-java/issues/437 and the comments.

#### Code example
Varies, not specific code but an interaction with Firestore server.

#### Stack trace
```
java.util.concurrent.ExecutionException: com.google.api.gax.rpc.UnavailableException: io.grpc.StatusRuntimeException: UNAVAILABLE: io exception at com.google.common.util.concurrent.AbstractFuture.getDoneValue(AbstractFuture.java:531) at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:512) at com.google.common.util.concurrent.AbstractFuture$TrustedFuture.get(AbstractFuture.java:83) at com.google.common.util.concurrent.ForwardingFuture.get(ForwardingFuture.java:62) at com.myapp.API3.api(API3.java:2789)

Caused by: io.grpc.netty.shaded.io.netty.channel.unix.Errors$NativeIoException: readAddress(..) failed: Connection reset by peer.
```
You can see another example in the thread above.
I see that 6.14.0 is out but I didn't see any reference to this issue. Any estimation on when a retry will be added? Thanks.

**Comment by ChiragMoradiya** [comment]
We also encountered this issue few days back; Any estimate - when this is going to be worked on?
