### ISSUE TITLE
Service account permission denied based on rules

### ISSUE THREAD

**Issue by brianfromoregon** [googleapis/java-firestore#431]
#### Environment details

OS type and version: windows 10
Java version: zulu 11
firestore version(s): 2.1.0

#### Steps to reproduce

  1. Run hello world example using service account json credentials that has Cloud Datastore User role.
  2. Permission denied stack trace when firestore is configured with below rules. I get the error on any operation I try, query or update.

```
rules_version = '2';
service cloud.firestore {
  match /databases/{database}/documents {
    match /{document=**} {
      allow read, write: if false;
    }
    
    match /users/{userId} {
    	allow read, write: if isOwner(userId);
    }
    
    function isOwner(userId) {
    	return request.auth.uid == userId;
    }
  }
}
```

However if you change the first rule from false to true, the java example using service account creds works fine as expected:
```
       allow read, write: if true;
```

That is strange because all the online docs say that service accounts are not affected by rules. My theory is that somehow the isOwner function causes the service account to get an error evaluating the rule? I suspect that because rule monitor shows a bunch of errors as I am doing my testing.

![image](https://user-images.githubusercontent.com/1198163/96632650-dd475500-12cc-11eb-9296-36c83dd8ff09.png)

**Comment by brianfromoregon** [comment]
Anton may have had a similar experience based on his SO comment https://stackoverflow.com/questions/51930891/how-to-get-firestore-rules-working-with-service-accounts#comment103736028_51931429

**Comment by brianfromoregon** [comment]
FYI I experience this behavior when running locally (win 10 + zulu) and on AWS lambda

**Comment by BenWhitehead** [comment]
@schmidt-sebastian Have you seen this happen before? I didn't think service accounts where impacted by rules.

**Comment by schmidt-sebastian** [comment]
Just a general comment - is `Cloud Datastore User` different from `Cloud Firestore User`?

And +1 to what @BenWhitehead said. Requests from the Server SDKs should not be evaluated against Security Rules. Security Rules are only used for third-party client requests from our Mobile SDKs.

**Comment by brianfromoregon** [comment]
I don't see a Cloud Firestore User role available.

**Comment by brianfromoregon** [comment]
I just verified this again today. I've been receiving the automated email from firebase with subject "[Firebase] Your Cloud Firestore database has insecure rules"

So I tried commenting this bit
```
    match /{document=**} {
      allow read, write: if true;
    }
```

And right away my Java batch process which runs on Win10 started throwing this error:

```
java.util.concurrent.ExecutionException: com.google.api.gax.rpc.PermissionDeniedException: io.grpc.StatusRuntimeException: PERMISSION_DENIED: Missing or insufficient permissions.
        at com.google.common.util.concurrent.AbstractFuture.getDoneValue(AbstractFuture.java:564)
        at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:443)
        at com.google.api.core.AbstractApiFuture.get(AbstractApiFuture.java:61)
        at greenhouse.TokenRefresher.run(TokenRefresher.java:60)
        at container.Main$RunWrapper.run(Main.java:95)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:830)
Caused by: com.google.api.gax.rpc.PermissionDeniedException: io.grpc.StatusRuntimeException: PERMISSION_DENIED: Missing or insufficient permissions.
        at com.google.api.gax.rpc.ApiExceptionFactory.createException(ApiExceptionFactory.java:55)
        at com.google.api.gax.grpc.GrpcApiExceptionFactory.create(GrpcApiExceptionFactory.java:72)
        at com.google.api.gax.grpc.GrpcApiExceptionFactory.create(GrpcApiExceptionFactory.java:60)
        at com.google.api.gax.grpc.ExceptionResponseObserver.onErrorImpl(ExceptionResponseObserver.java:82)
        at com.google.api.gax.rpc.StateCheckingResponseObserver.onError(StateCheckingResponseObserver.java:86)
        at com.google.api.gax.grpc.GrpcDirectStreamController$ResponseObserverAdapter.onClose(GrpcDirectStreamController.java:149)
        at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:434)
        at io.grpc.internal.ClientCallImpl.access$500(ClientCallImpl.java:66)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:763)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:742)
        at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
        at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
        ... 6 more
Caused by: io.grpc.StatusRuntimeException: PERMISSION_DENIED: Missing or insufficient permissions.
        at io.grpc.Status.asRuntimeException(Status.java:533)
        ... 13 more
```

**Comment by schmidt-sebastian** [comment]
Do you mind filing a customer support ticket with your project and credential information? https://cloud.google.com/support-hub

We don't use Rules in the Server SDKs (in fact, it is an often requested feature that we haven't gotten around to yet), so something else must be going on here. To figure this out, we would need to look at your project data.

**Comment by brianfromoregon** [comment]
This is resolved now. 
Old code which was influenced by the Rules:
```
    var firestoreOptions =
        FirestoreOptions.getDefaultInstance().toBuilder()
            .setCredentials(GoogleCredentials.fromStream(credentials))
            .build();
    var firestore = firestoreOptions.getService();
```

New code which is not influenced by the Rules:
```
    var options = FirebaseOptions.builder()
        .setCredentials(GoogleCredentials.fromStream(credentials))
        .build();

    FirebaseApp.initializeApp(options);
    var firestore = FirestoreClient.getFirestore();
```

Tricky one.

**Comment by brianfromoregon** [comment]
More detail, both old and new code used this dependency:
```
    implementation 'com.google.cloud:google-cloud-firestore:2.1.0'
```
And new code uses API that requires adding a new dependency:
```
    implementation 'com.google.firebase:firebase-admin:7.0.1'
```

**Comment by schmidt-sebastian** [comment]
Thanks for following up.  I am glad you managed to find a solution.
