### ISSUE TITLE
"FieldValue.delete() is not supported at field"

### ISSUE THREAD

**Issue by alamothe** [googleapis/java-firestore#480]
#### Environment details

1. Specify the API at the beginning of the title. For example, "BigQuery: ...").
2. OS type and version: `MacOS`
3. Java version: `11`
4. firestore version(s): `com.google.firebase:firebase-admin:7.0.1`

#### Steps to reproduce

Exception thrown while trying to delete a field:

```kt
batch.update(docRef, FieldPath.of("abc", "184.174.14.109", "xyz"), FieldValue.delete())
```

Error:
```
java.lang.IllegalArgumentException: FieldValue.delete() is not supported at field 'abc.`184`.`174`.`14`.`109`.xyz'.

	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:217)
	at com.google.cloud.firestore.UserDataConverter.encodeValue(UserDataConverter.java:100)
	at com.google.cloud.firestore.UserDataConverter.encodeValue(UserDataConverter.java:163)
	at com.google.cloud.firestore.UserDataConverter.encodeValue(UserDataConverter.java:163)
	at com.google.cloud.firestore.UserDataConverter.encodeValue(UserDataConverter.java:163)
	at com.google.cloud.firestore.DocumentSnapshot.fromObject(DocumentSnapshot.java:91)
	at com.google.cloud.firestore.UpdateBuilder.performUpdate(UpdateBuilder.java:498)
	at com.google.cloud.firestore.UpdateBuilder.performUpdate(UpdateBuilder.java:486)
	at com.google.cloud.firestore.UpdateBuilder.update(UpdateBuilder.java:396)
	at com.google.cloud.firestore.DocumentReference.update(DocumentReference.java:279)
```

This happens before even reaching the backend, in client code.

I am also wondering if there is any workaround until this is resolved?

**Comment by athakor** [comment]
@alamothe Thanks for raising this issue. I follow your step and able to reproduce this issue. The cause of issue is that `firebase-admin-7.0.1` use the `firestore 1.35.0` version and that is quite old. I believe these issue is resolved in latest releases, see [here](https://github.com/googleapis/java-firestore/pull/295).

To fix these problem exclude `google-cloud-firestore:1.35.0` from `firebase-admin-7.0.1` and explicitly add the latest version of firestore dependency  i.e `google-cloud-firestore:2.1.0`  like below.

**pom.xml**

```javascript
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>org.example</groupId>
    <artifactId>issue-480</artifactId>
    <version>1.0-SNAPSHOT</version>
    <dependencies>
        <dependency>
            <groupId>com.google.firebase</groupId>
            <artifactId>firebase-admin</artifactId>
            <version>7.0.1</version>
            <exclusions>
                <exclusion>
                    <groupId>com.google.cloud</groupId>
                    <artifactId>google-cloud-firestore</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>com.google.cloud</groupId>
            <artifactId>google-cloud-firestore</artifactId>
            <version>2.1.0</version>
        </dependency>
    </dependencies>
</project>
```
**Sample**
```javascript
import com.google.api.core.ApiFuture;
import com.google.auth.oauth2.GoogleCredentials;
import com.google.cloud.ServiceOptions;
import com.google.cloud.firestore.DocumentReference;
import com.google.cloud.firestore.DocumentSnapshot;
import com.google.cloud.firestore.FieldPath;
import com.google.cloud.firestore.FieldValue;
import com.google.cloud.firestore.Firestore;
import com.google.cloud.firestore.FirestoreOptions;
import com.google.cloud.firestore.WriteBatch;
import com.google.cloud.firestore.WriteResult;
import com.google.common.collect.ImmutableMap;

import java.io.IOException;
import java.util.HashMap;
import java.util.Map;
import java.util.concurrent.ExecutionException;

public class Test {
    public static void main(String[] args) throws ExecutionException, InterruptedException, IOException {

        FirestoreOptions firestoreOptions =
                FirestoreOptions.getDefaultInstance().toBuilder()
                        .setProjectId(ServiceOptions.getDefaultProjectId())
                        .setCredentials(GoogleCredentials.getApplicationDefault())
                        .build();
        Firestore db = firestoreOptions.getService();
        DocumentReference docRef = db.collection("col1").document("doc1");

        Map<String,Object> xyzMap = new HashMap();
        xyzMap.put("xyz","data");

        Map<String,Object> dotMap = new HashMap();
        dotMap.put("184.174.14.109",xyzMap);

        Map<String, Object> data = new HashMap();
        data.put("abc", dotMap);
        ApiFuture<WriteResult> writeResult = docRef.update(data);

        System.out.println("Before FieldValue.delete");
        DocumentSnapshot documentSnapshot = docRef.get().get();
        System.out.println(documentSnapshot.getData());

        FieldPath path = FieldPath.of("abc", "184.174.14.109", "xyz");
        docRef.update(path, FieldValue.delete()).get();

        System.out.println("After FieldValue.delete");
        documentSnapshot = docRef.get().get();
        System.out.println(documentSnapshot.getData());
    }
}
```

**Output**
```
Before FieldValue.delete
{abc={184.174.14.109={xyz=data}}}
After FieldValue.delete
{abc={184.174.14.109={}}}
```

Please let us know if this helps!

**Comment by alamothe** [comment]
Interesting! Thank you for answer. I'm actually pretty sure that we don't need `firebase-admin` at all, it was what we started with initially based on some docs. I will make the switch and let you know.

**Comment by alamothe** [comment]
Works! Closing now, thanks!
