### ISSUE TITLE
Snapshot listener gets a regular callback with 'Received unexpected EOS on empty DATA frame from server' exception

### ISSUE THREAD

**Issue by menulis** [googleapis/java-firestore#822]
We are using Firestore snapshot listeners on documents and queries to receive callbacks whenever documents are updated.
The [documentation](https://cloud.google.com/firestore/docs/query-data/listen#java_6) states that "after an error, the listener will not receive any more events, and there is no need to detach your listener“. However, once a snapshot listener is created, we regularly  (around every hour at least for documents that do not get any updates) receive an error callback, i.e. `EventListener::onEvent` with non-null second `error` argument that is of `FirestoreException` type that looks like a gRPC idle timeout or similar:

```
io.grpc.StatusRuntimeException: INTERNAL: Received unexpected EOS on empty DATA frame from server
	at io.grpc.Status.asRuntimeException(Status.java:535)
	... 10 common frames omitted
Wrapped by: com.google.api.gax.rpc.InternalException: io.grpc.StatusRuntimeException: INTERNAL: Received unexpected EOS on empty DATA frame from server
	at com.google.api.gax.rpc.ApiExceptionFactory.createException(ApiExceptionFactory.java:67)
	at com.google.api.gax.grpc.GrpcApiExceptionFactory.create(GrpcApiExceptionFactory.java:72)
	at com.google.api.gax.grpc.GrpcApiExceptionFactory.create(GrpcApiExceptionFactory.java:60)
	at com.google.api.gax.grpc.ExceptionResponseObserver.onErrorImpl(ExceptionResponseObserver.java:82)
	at com.google.api.gax.rpc.StateCheckingResponseObserver.onError(StateCheckingResponseObserver.java:86)
	at com.google.api.gax.grpc.GrpcDirectStreamController$ResponseObserverAdapter.onClose(GrpcDirectStreamController.java:149)
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:557)
	at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:69)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:738)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:717)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133)
	... 3 common frames omitted
Wrapped by: com.google.api.gax.rpc.ApiException: com.google.api.gax.rpc.InternalException: io.grpc.StatusRuntimeException: INTERNAL: Received unexpected EOS on empty DATA frame from server
	at com.google.cloud.firestore.Watch.lambda$closeStream$2(Watch.java:339)
	... 6 common frames omitted
Wrapped by: com.google.cloud.firestore.FirestoreException: com.google.api.gax.rpc.InternalException: io.grpc.StatusRuntimeException: INTERNAL: Received unexpected EOS on empty DATA frame from server
	at com.google.cloud.firestore.FirestoreException.forApiException(FirestoreException.java:104)
	at com.google.cloud.firestore.Watch.lambda$closeStream$2(Watch.java:336)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:831)
```

If we do not "handle" these errors by recreating the snapshot listener, the callback would in most of the cases still be called on a snapshot listener upon update regardless of the fact that previously there was a callback with the EOS error invoked already invoked on the same listener. In other words, it seems that there is no need to treat EOS exceptions as errors upon which "the listener will not receive any more events“, but this neither documented nor expected behaviour.

#### Environment details

Platform: GKE
Firestore version: 3.0.7

#### Steps to reproduce

  1. Create a snapshot listener on a document
  2. Wait for 1 hour
  3. EventListener::onEvent callback is called with non-null error parameter that is FirestoreException wrapping an EOS situation

#### Related issues
- https://github.com/grpc/grpc-java/issues/5944

**Comment by schmidt-sebastian** [comment]
Sorry for the long delay here and thanks for reporting this. I think the problem is that https://github.com/googleapis/java-firestore/blob/main/google-cloud-firestore/src/main/java/com/google/cloud/firestore/Watch.java#L324 does not actually close the stream, hence you get further callbacks. We will get this fixed.

**Comment by safarmer** [comment]
So it seems like the fix that was merged only covers the case where the stream was not closed. It does not handle the fact that these errors are happening? Is there a planned fix for the underlying connection being closed from an unexpected EOS?

**Comment by ahetawal-p** [comment]
@menulis doing this 

> If we do not "handle" these errors by recreating the snapshot listener,

Does it fixes your problem and listeners work as expected for you ?

**Comment by schmidt-sebastian** [comment]
You should only get an error if the stream closed with an unrecoverable error and when you do get an error you should only get it once.

**Comment by ahetawal-p** [comment]
Thanks for your reply @schmidt-sebastian, so certainly we do get that error, but what is recommended way to recover from it. As after this our backend process is useless and stops listening updates. We need to restart the app to get it working ..

Retrying keeps on giving us the same error again and again as mentioned here https://github.com/googleapis/java-firestore/issues/866

**Comment by safarmer** [comment]
@schmidt-sebastian I think the question I have is are the underlying disconnections a part of this issue or should we file a separate ticket? 

It seems like the title of the issue is describing our exact issue. I was under the assumption that having a listener stay connected to Firestore was core functionality. Perhaps if this is working as intended, the documentation needs to be updated to indicate that the connection will be reset if there are no updates received?

**Comment by schmidt-sebastian** [comment]
PR in review that would catch this exact error and re-open the stream: https://github.com/googleapis/java-firestore/pull/875
